### ISSUE TITLE
Failed to start - Exit Code -1073741515

### ISSUE THREAD

**Issue by ThijmenGThN** [sh1ny/WindowsGSM.ArkSurvivalAscended#1]
Thank you for creating this plugin so swiftly to run Ascended, unfortunately it does not seem to run for me though, I've provided the error message from the console below. 

If you are able to point me to where I can find the crash log files I'd be more than happy to provide those as well.

```
[#1] [ERROR] Exit Code: -1073741515
[#1] Server: Fail to start
```

Would love to get this working, thanks!

**Comment by sh1ny** [comment]
I had to install steam for it to work, no idea otherwise.

**Comment by sh1ny** [comment]
Could be also that you're missing some dependencies,like vcredist, directx etc. not sure.

**Comment by ThijmenGThN** [comment]
Both seemed to be the case, thank you for the guidance!

Closing this issue now 😄
