### ISSUE TITLE
BattlEye Issue

### ISSUE THREAD

**Issue by i812** [sh1ny/WindowsGSM.ArkSurvivalAscended#10]
Hello,

I have the parameter -nobattleye set in the Server Start Param section and I can confirm that it shows up in the WindowsGSM.cfg file as, serverparam="-nobattleye" but when I launch my server it still runs with BattlEye enabled.  Am I doing something wrong?

**Comment by sh1ny** [comment]
Here's how i run it:

https://i.imgur.com/tkcNCkt.png

You can note that there is no battleye loaded. 

Here's with battleye:

https://i.imgur.com/71WY8wu.png

Note how it says "Server initializing with BattleEye".

So as far as parsing the argument, it works.
make sure you're running the latest version of the plugin ( 1.2 ).

EDIT: OK i figured it out. You're using ONLY -nobattleye . Try putting something like:

?RCONPort=27021 -nobattleye

And it will work.

**Comment by sh1ny** [comment]
I have updated the plugin to cover your use case. Update to 1.21 and you can use only "-nobattleye" and it will work.

**Comment by i812** [comment]
Thanks for the quick responses.  I took my dog for a walk and when I got
back your answer was waiting for me.

I really appreciate your help.
