### ISSUE TITLE
Update server

### ISSUE THREAD

**Issue by TesterNA** [sh1ny/WindowsGSM.ArkSurvivalAscended#12]
today server got one new "stability patch" [12678373](https://steamdb.info/patchnotes/12678373/), but my server still 12643738 build version and on clicking update windwowsgsm saying 
Checking: Version (12643738) => ()
Server: Updated ()
and version not changing, nothing downloading

**Comment by sh1ny** [comment]
Hey @TesterNA . Yes, the updates are pushed slower for the private servers. There's nothing i can do from the plugin side :)

**Comment by TesterNA** [comment]
> Hey @TesterNA . Yes, the updates are pushed slower for the private servers. There's nothing i can do from the plugin side :)

hey. yeah, saw it in few minutes after creating this issue, thats why closed it immediatelly. Sorry for bother)
