### ISSUE TITLE
How do you start the server with the app?

### ISSUE THREAD

**Issue by dperlop** [sh1ny/WindowsGSM.ArkSurvivalAscended#2]
Im trying to start the server but nothing happens, did you follow any tuto steps?

**Comment by sh1ny** [comment]
Hey, did you try to click "Toggle Console" after you click start ?

**Comment by dperlop** [comment]
Now, thanks, where you can change startup parameters?

**Comment by sh1ny** [comment]
Click on the server, after it's installed, and click edit config on the lower left side of the UI:

https://i.imgur.com/iw1ZtJU.png
