### ISSUE TITLE
Tried for 5 hours to change MaxPlayers

### ISSUE THREAD

**Issue by TheBurntPeanut** [sh1ny/WindowsGSM.ArkSurvivalAscended#4]
I cannot for the life of me figure out how to change MaxPlayers.

I change max players from 70 to 40 in gameusersettings.ini, as well as under "max players" in the "edit config" button of windows gsm, but every time the server starts the player count goes to 70, gameusersettings.ini changes back to 70, and "max players" under "edit config" stays at 40, seemingly doing nothing.

I have tried setting gameusersettings.ini to read-only, but it doesn't do anything, the setting in gameusersettings.ini stays at 40 when it is read only, but the player count in ark still goes to 70.

I also have it in the start parameter as well (MaxPlayers=40?RCONEnabled=False?RCONPort=XXXXX? -BattlEye -mods=928708,900062,927131,912902,926956,914844,916922,908148,929785)
I saw what you said about checking if it says 7777, and that means parameters aren't working, but unfortunately i'm not sure what any of that means, nor do I know where to type that thing in you said to check for 7777, but I think the parameters are working because when I switched from nobattleeye to battleeye, it changed, so I think they are working, but again, I am completely clueless about what that part of the readme means, or how to utilize it.

Any help would be greatly appreciated! Thanks again for making this plugin!

**Comment by SlixX95** [comment]
try start command: -WinLiveMaxPlayers=100

**Comment by TheBurntPeanut** [comment]
That worked! Thank you!

**Comment by sh1ny** [comment]
Parameters are working, it seems like ARK is ignoring the maxplayers parameter. Let me see what i can do with -WinLiveMaxPlayers.

**Comment by sh1ny** [comment]
@SlixX95 thank you for the hint, i have implemented that in 1.1 version of the plugin. Let me know if it works.

**Comment by sh1ny** [comment]
Closing as fixed, re-open if the universe implodes.
