### ISSUE TITLE
Stop server doesn't force save

### ISSUE THREAD

**Issue by Naarin** [sh1ny/WindowsGSM.ArkSurvivalAscended#5]
The command stop doesn't save the server it could be useful to stop cleanly the server. The command "quit" save and shutdown the server.

**Comment by TheBurntPeanut** [comment]
Hey, was just posting my own issue when I saw yours, I noticed that as well, I just changed autosaveinterval to 5 minutes in gameusersettings.ini (or game.ini, forget which one), and then also, before I close the server, if I happen to be on, i type "admincheat saveworld" after enabling cheats. But I'm with ya there, that'd be dope if there was an exit save, but just incase it doesn't get added, that's how I've been dealing with it.

**Comment by Naarin** [comment]
You can also type "quit" in the console to save and shutdown :) i am trying to find a way to bind it to stop somehow

**Comment by Naarin** [comment]
Found it !
in plugins\ArkSurvivalAscended.cs\ArkSurvivalAscended.cs
change this
await Task.Run(() =>
            {
                p.Kill();
            });
by
await Task.Run(() =>
            {
                // p.Kill();
                Functions.ServerConsole.SetMainWindow(p.MainWindowHandle);
                Functions.ServerConsole.SendWaitToMainWindow("quit");
				// p.CloseMainWindow();
                Functions.ServerConsole.SendWaitToMainWindow("{ENTER}");
            });

**Comment by sh1ny** [comment]
I have added experimental saving before exiting in the newest 1.1 version of the plugin. Please check it out locally, before updating the live servers.

**Comment by sh1ny** [comment]
Closing as fixed, reopen if something goes ham.
